// Generated by gencpp from file motor_control/Position.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_MESSAGE_POSITION_H
#define MOTOR_CONTROL_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : desiredPos(0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : desiredPos(0)  {
    }



   typedef int32_t _desiredPos_type;
  _desiredPos_type desiredPos;




  typedef boost::shared_ptr< ::motor_control::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::motor_control::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::motor_control::Position > PositionPtr;
typedef boost::shared_ptr< ::motor_control::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_control': ['/home/legged/Legged/catkin_ws/src/motor_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43e7fe6eb258ef55e9b2f74c52038828";
  }

  static const char* value(const ::motor_control::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43e7fe6eb258ef55ULL;
  static const uint64_t static_value2 = 0xe9b2f74c52038828ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control/Position";
  }

  static const char* value(const ::motor_control::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 desiredPos\n\
";
  }

  static const char* value(const ::motor_control::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desiredPos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control::Position_<ContainerAllocator>& v)
  {
    s << indent << "desiredPos: ";
    Printer<int32_t>::stream(s, indent + "  ", v.desiredPos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_MESSAGE_POSITION_H
