#ifndef __SPI_H__
#define __SPI_H__

#define HIGH 0xFF
#define LOW 0x00

#define IMU_SPI_PERIPH		SYSCTL_PERIPH_SSI2
#define IMU_SPI_PORT_PERIPH	SYSCTL_PERIPH_GPIOD
#define IMU_SPI_SSI_BASE	SSI2_BASE
#define IMU_SPI_PORT_BASE 	GPIO_PORTD_BASE
#define IMU_SPI_CLK_PIN 	GPIO_PIN_3
#define IMU_SPI_RX_PIN 		GPIO_PIN_0
#define IMU_SPI_TX_PIN 		GPIO_PIN_1
#define IMU_SPI_CLK_MUX		GPIO_PD3_SSI2CLK
#define IMU_SPI_RX_MUX		GPIO_PD0_SSI2XDAT1
#define IMU_SPI_TX_MUX		GPIO_PD1_SSI2XDAT0

#define IMU_CS_PERIPH		SYSCTL_PERIPH_GPION
#define IMU_CS_PORT_BASE 	GPIO_PORTN_BASE
#define IMU_CS_PIN	        GPIO_PIN_2

#define IMU_RST_PERIPH		SYSCTL_PERIPH_GPIOC
#define IMU_RST_PORT_BASE 	GPIO_PORTC_BASE
#define IMU_RST_PIN	        GPIO_PIN_7

#define IMU_IRQ_PERIPH		SYSCTL_PERIPH_GPION
#define IMU_IRQ_PORT_BASE 	GPIO_PORTN_BASE
#define IMU_IRQ_PIN		GPIO_PIN_3
#define IMU_IRQ_INT		INT_GPION


uint8_t SpiTransfer(uint8_t _byte);
int16_t SpiTransfer16(int16_t _byte);
void init_spi();
void init_spi16();
void IMU_CS(uint8_t HighLow);
void IMU_RST(uint8_t HighLow);

#endif
